// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
    {
        "name": "TJS",
        "status": true,
        "description": "Main Plugin for TJS code.",
        "parameters": {}
    }
];
